In [7]:
a = 100.789; print(type(a))

<class 'float'>


In [9]:
a = 5.21; a = float(a); print(type(a))

<class 'float'>


In [14]:
a = 2.59; a = int(a); print(type(a))

<class 'int'>


print () : 값을 출력 type () : 변수의 type
type의 종류
float : 실수
int : 정수
str : 문자열 , 문자열을 표기할때는 따옴표''로 묶는다. ex) '가나다'

In [22]:
a = '가나다라마'; print(type(a)); print(a[-2])

<class 'str'>
라


In [27]:
a = '58753.2045'; a = list(a); print(type(a)); print(a); print(a[-2])

<class 'list'>
['5', '8', '7', '5', '3', '.', '2', '0', '4', '5']
4


In [37]:
c = [[1, '미국산문'],'2', [3, '영어학개론']]; print(type(c)); print(c[0]); print(c[1]); print(c[2])

<class 'list'>
[1, '미국산문']
2
[3, '영어학개론']


In [38]:
a = (1,'2', [3, '4']); print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'tuple'>
1
2
[3, '4']


In [48]:
a=[1,2,'ab',[4,5]], print(a)

([1, 2, 'ab', [4, 5]], None)


python [#]는 각각
[0] : 1번째
[1] : 2번째
[-1] : 제일 마지막 것
[-2] : 뒤에서 두번째를 지칭한다.
type () : tuple type [] : list
list속에는 또 다른 list가 생성 가능 하다. ex) a=[1,2,'ab',[4,5]]

In [52]:
a =	{"가": "호랑이", "나": "러시아", "s": '스코틀랜드'}
print(type(a))
print(a["s"]);print(a["나"])

<class 'dict'>
스코틀랜드
러시아


dictionary : {}로 묶는다. / type () : tuple type [] : list
; 다음 행

In [53]:
a=[(1,2,3), (3,8,0)]
print(type(a))
a

<class 'list'>


[(1, 2, 3), (3, 8, 0)]

ㄴ 2x3의 행렬 형태

In [55]:
import numpy as np
b = np.array(a)
print(b)
print(type(b))

[[1 2 3]
 [3 8 0]]
<class 'numpy.ndarray'>


import : 하드디스크에 저장된 것을 메모리에 불러오는 작업 (directory의 정보를 메모리에 띄우기) 
numpy : import를 사용해 메모리로 불러와야함 (numpy - directory에 존재한다.) a는 numpy내에 존재하는 함수를 지칭한다.
if) import numpy라고만 쓰면 b = numpy.array(a)라고 써야함 : 그냥 array(a)만 쓰면 numpy가 지정되지 않았기 때문에 오류발생. 
as np (타이핑의 편의상 설정)

In [58]:
print(b*b)

[[ 1  4  9]
 [ 9 64  0]]


ㄴ axb 행렬과 곱할 수 있는 행렬의 형태는 bxc, bxb는 2x3와 2x3의 곱 -> 실제론 행렬이 아니라, 형태만 행렬인 것으로 도출

In [59]:
c = np.matrix(b)
print(c)
print(type(c))

[[1 2 3]
 [3 8 0]]
<class 'numpy.matrixlib.defmatrix.matrix'>


np내에 존재하는 matrix (함수)
<class 'numpy.matrixlib.defmatrix.matrix'> : c의 타입을 의미한다.

In [ ]:
c*c

In [ ]:
c*c.T

T : transpose로, 본래 c가 2x3 matrix였는데 T를 이용해 flip함으로써 3x2의 형태로 변화시킨다. 따라서 2x2의 행렬이 도출