In [11]:
a = 1

In [2]:
type (a)

int

In [3]:
a=1.1

In [4]:
type (a)

float

In [5]:
int(float(int(a)))

1

In [6]:
a=1; a=float(a); print(type(a))

<class 'float'>


In [7]:
a=1.2; a=int(a); print(type(a))

<class 'int'>


In [8]:
a='123'

In [9]:
a

'123'

In [10]:
type(a)

str

In [20]:
a='abc'

In [21]:
a[1]

'b'

In [22]:
a[0]

'a'

In [23]:
a[-1]

'c'

In [24]:
a=[1,2,3]

In [25]:
a

[1, 2, 3]

In [26]:
type(a)

list

In [27]:
a=[1,2,'ab',[4,5]]

In [28]:
a[0]

1

In [29]:
a[-1]

[4, 5]

In [30]:
a[-2]

'ab'

In [31]:
a[-1][0]

4

In [33]:
a = '123'; a = list(a);

In [34]:
a

['1', '2', '3']

In [35]:
a =	{"a": "apple", "b": "orange", "c": 2014}
print(type(a))
print(a["a"])

<class 'dict'>
apple


variable dictionary, have to use {}, unlike list.. (숙제 summary 예시)

In [36]:
a["b"]

'orange'

In [2]:
a=[(1,2,3), (3,8,0)]
print(type(a))
a

<class 'list'>


[(1, 2, 3), (3, 8, 0)]

ㄴ 2x3의 행렬

In [5]:
import numpy as np
b = np.array(a)
print(b)
print(type(b))

[[1 2 3]
 [3 8 0]]
<class 'numpy.ndarray'>


import : 하드디스크에 저장된 것을 메모리에 불러오는 작업 (directory의 정보를 메모리에 띄우기)
numpy : basic에 존재하지 않기 때문에 import를 이용해 메모리로 불러와야함 (numpy - directory에 존재한다.)
만약 import numpy라고만 쓰면
b = numpy.array(a)라고 써야함 : 그냥 array(a)만 쓰면 numpy가 지정되지 않았기 때문에 에러. a는 numpy내에 존재하는 함수
as np (타이핑의 편의상 설정)


In [6]:
print(b*b)

[[ 1  4  9]
 [ 9 64  0]]


ㄴ axb 행렬과 곱할 수 있는 행렬의 형태는 bxc
이 경우, bxb는 2x3와 2x3의 곱 -> 사실은 행렬이 아니라, 형태만 행렬인 것으로 도출


c = np.matrix(b)
print(c)
print(type(c))

matrix (새로운 함수)
<class 'numpy.matrixlib.defmatrix.matrix'> : c의 타입

In [8]:
c*c

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [9]:
c*c.T

matrix([[14, 19],
        [19, 73]])

T : transpose로, 본래 c가 2x3 matrix였는데 T를 이용해 flip함으로써 3x2의 형태로 변화시킨다. 따라서 2x2의 행렬이 도출

객체 지향과 class

In [10]:
 s = "abcdef"

In [11]:
print(type(s))

<class 'str'>
